package de.yoadey.choreomusic.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import de.yoadey.choreomusic.model.Song;
import de.yoadey.choreomusic.model.Track;

import de.yoadey.choreomusic.model.SongDao;
import de.yoadey.choreomusic.model.TrackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig songDaoConfig;
    private final DaoConfig trackDaoConfig;

    private final SongDao songDao;
    private final TrackDao trackDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        trackDaoConfig = daoConfigMap.get(TrackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        songDao = new SongDao(songDaoConfig, this);
        trackDao = new TrackDao(trackDaoConfig, this);

        registerDao(Song.class, songDao);
        registerDao(Track.class, trackDao);
    }
    
    public void clear() {
        songDaoConfig.clearIdentityScope();
        trackDaoConfig.clearIdentityScope();
    }

    public SongDao getSongDao() {
        return songDao;
    }

    public TrackDao getTrackDao() {
        return trackDao;
    }

}
