package de.yoadey.choreomusic.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SONG".
*/
public class SongDao extends AbstractDao<Song, Long> {

    public static final String TABLENAME = "SONG";

    /**
     * Properties of entity Song.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uri = new Property(1, String.class, "uri", false, "URI");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Length = new Property(3, long.class, "length", false, "LENGTH");
        public final static Property Amplitudes = new Property(4, byte[].class, "amplitudes", false, "AMPLITUDES");
        public final static Property LastUsed = new Property(5, java.util.Date.class, "lastUsed", false, "LAST_USED");
        public final static Property FileSupportsTracks = new Property(6, boolean.class, "fileSupportsTracks", false, "FILE_SUPPORTS_TRACKS");
    }

    private DaoSession daoSession;


    public SongDao(DaoConfig config) {
        super(config);
    }
    
    public SongDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SONG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"URI\" TEXT NOT NULL ," + // 1: uri
                "\"TITLE\" TEXT," + // 2: title
                "\"LENGTH\" INTEGER NOT NULL ," + // 3: length
                "\"AMPLITUDES\" BLOB," + // 4: amplitudes
                "\"LAST_USED\" INTEGER NOT NULL ," + // 5: lastUsed
                "\"FILE_SUPPORTS_TRACKS\" INTEGER NOT NULL );"); // 6: fileSupportsTracks
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SONG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Song entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUri());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getLength());
 
        byte[] amplitudes = entity.getAmplitudes();
        if (amplitudes != null) {
            stmt.bindBlob(5, amplitudes);
        }
        stmt.bindLong(6, entity.getLastUsed().getTime());
        stmt.bindLong(7, entity.getFileSupportsTracks() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Song entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUri());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getLength());
 
        byte[] amplitudes = entity.getAmplitudes();
        if (amplitudes != null) {
            stmt.bindBlob(5, amplitudes);
        }
        stmt.bindLong(6, entity.getLastUsed().getTime());
        stmt.bindLong(7, entity.getFileSupportsTracks() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(Song entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Song readEntity(Cursor cursor, int offset) {
        Song entity = new Song( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // uri
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.getLong(offset + 3), // length
            cursor.isNull(offset + 4) ? null : cursor.getBlob(offset + 4), // amplitudes
            new java.util.Date(cursor.getLong(offset + 5)), // lastUsed
            cursor.getShort(offset + 6) != 0 // fileSupportsTracks
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Song entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUri(cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLength(cursor.getLong(offset + 3));
        entity.setAmplitudes(cursor.isNull(offset + 4) ? null : cursor.getBlob(offset + 4));
        entity.setLastUsed(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setFileSupportsTracks(cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Song entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Song entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Song entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
