package de.yoadey.choreomusic.model;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRACK".
*/
public class TrackDao extends AbstractDao<Track, Long> {

    public static final String TABLENAME = "TRACK";

    /**
     * Properties of entity Track.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FileId = new Property(1, long.class, "fileId", false, "FILE_ID");
        public final static Property Position = new Property(2, long.class, "position", false, "POSITION");
        public final static Property Label = new Property(3, String.class, "label", false, "LABEL");
        public final static Property Color = new Property(4, int.class, "color", false, "COLOR");
    }

    private Query<Track> song_TracksQuery;

    public TrackDao(DaoConfig config) {
        super(config);
    }
    
    public TrackDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRACK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FILE_ID\" INTEGER NOT NULL ," + // 1: fileId
                "\"POSITION\" INTEGER NOT NULL ," + // 2: position
                "\"LABEL\" TEXT NOT NULL ," + // 3: label
                "\"COLOR\" INTEGER NOT NULL );"); // 4: color
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_TRACK_POSITION ON \"TRACK\"" +
                " (\"POSITION\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRACK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Track entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFileId());
        stmt.bindLong(3, entity.getPosition());
        stmt.bindString(4, entity.getLabel());
        stmt.bindLong(5, entity.getColor());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Track entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFileId());
        stmt.bindLong(3, entity.getPosition());
        stmt.bindString(4, entity.getLabel());
        stmt.bindLong(5, entity.getColor());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Track readEntity(Cursor cursor, int offset) {
        Track entity = new Track( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // fileId
            cursor.getLong(offset + 2), // position
            cursor.getString(offset + 3), // label
            cursor.getInt(offset + 4) // color
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Track entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFileId(cursor.getLong(offset + 1));
        entity.setPosition(cursor.getLong(offset + 2));
        entity.setLabel(cursor.getString(offset + 3));
        entity.setColor(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Track entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Track entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Track entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "tracks" to-many relationship of Song. */
    public List<Track> _querySong_Tracks(long fileId) {
        synchronized (this) {
            if (song_TracksQuery == null) {
                QueryBuilder<Track> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FileId.eq(null));
                song_TracksQuery = queryBuilder.build();
            }
        }
        Query<Track> query = song_TracksQuery.forCurrentThread();
        query.setParameter(0, fileId);
        return query.list();
    }

}
